name: Deploy

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies && Deploy
      run: |
        npm i
        now --token ${{ secrets.NOW_TOKEN }}
