name: Deploy

on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy
      run: |
        npm i
        now --token ${{ secrets.NOW_TOKEN }}
