name: CI

on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Echo the greeting's time
      run: echo 'The time was ${{ steps.hello.outputs.time }}.'


    - name: Deploy
      run: |
        ls
        npm -v
        npm i
        now --token ${{ secrets.NOW_TOKEN }}
